"use server";

import { createClient } from "@/utils/supabase/server";
import { revalidatePath } from "next/cache";

import { logger } from '@/lib/logger';
interface OrganizationData {
  name: string;
  description: string;
  address: string;
  phone: string;
  website: string;
  industry: string;
}

// Generate random invitation code
function generateInvitationCode(): string {
  const chars = 'ABCDEFGHIJKLMNPQRSTUVWXYZ123456789'; // Exclude O and 0 to avoid confusion
  let result = '';
  for (let i = 0; i < 8; i++) {
    result += chars.charAt(Math.floor(Math.random() * chars.length));
  }
  return result;
}

// Join organization with invitation code
export async function joinOrganization(invitationCode: string): Promise<{
  success: boolean;
  message: string;
}> {
  try {
    const supabase = await createClient();
    
    // Get current user
    const { data: { user }, error: userError } = await supabase.auth.getUser();
    
    if (userError || !user) {
      return { success: false, message: "User not authenticated" };
    }

    // Find organization by invitation code (case-insensitive)
    const { data: organization, error: orgError } = await supabase
      .from("organizations")
      .select("id, name, is_active")
      .eq("inv_code", invitationCode.toUpperCase())
      .maybeSingle();

    if (orgError) {
      logger.error("Database error:", orgError);
      return { success: false, message: "Failed to verify invitation code" };
    }

    if (!organization) {
      return { 
        success: false, 
        message: "Invalid or expired invitation code. The code may have been regenerated by your organization admin. Please contact your admin for the latest invitation code." 
      };
    }

    if (!organization.is_active) {
      return { 
        success: false, 
        message: `The organization "${organization.name}" is currently inactive. Please contact the organization admin.` 
      };
    }

    // Check if user already has membership (either same org or different org)
    const { data: existingMembership } = await supabase
      .from("organization_members")
      .select("id, organization_id, is_active, organization:organizations(name)")
      .eq("user_id", user.id)
      .maybeSingle();

    if (existingMembership) {
      const orgName = (existingMembership.organization as unknown as { name: string })?.name || 'another organization';

      // Attempting to join a different organization while membership exists
      if (existingMembership.organization_id !== organization.id) {
        return { 
          success: false, 
          message: `You are already a member of "${orgName}". Please contact your admin if you need to switch organizations.` 
        };
      }

      // Membership already exists for this organization
      if (!existingMembership.is_active) {
        const { error: reactivateError } = await supabase
          .from("organization_members")
          .update({
            is_active: true,
            employment_status: 'active',
            updated_at: new Date().toISOString()
          })
          .eq("id", existingMembership.id);

        if (reactivateError) {
          logger.error("Failed to reactivate membership:", reactivateError);
          return { success: false, message: "Failed to reactivate your membership. Please try again." };
        }

        revalidatePath("/");
        return { 
          success: true, 
          message: `Your access to "${organization.name}" has been reactivated. Welcome back!` 
        };
      }

      // Already active member
      return { 
        success: true, 
        message: `You are already an active member of "${organization.name}".` 
      };
    }

    // Create organization member record
    const { error: memberError } = await supabase
      .from("organization_members")
      .insert({
        organization_id: organization.id,
        user_id: user.id,
        employee_id: `EMP-${Date.now()}`, // Generate temporary employee ID
        hire_date: new Date().toISOString().split('T')[0],
        employment_status: 'active',
        contract_type: 'permanent',
        is_active: true,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
      });

    if (memberError) {
      logger.error("Member creation error:", memberError);
      // Berikan pesan error yang lebih spesifik agar mudah debug
      return { 
        success: false, 
        message: memberError.message || "Failed to join organization. Please try again." 
      };
    }

    revalidatePath("/");
    return { 
      success: true, 
      message: `Successfully joined "${organization.name}"! Welcome to your organization.` 
    };

  } catch (error: unknown) {
    logger.error("Join organization error:", error);
    return { 
      success: false, 
      message: "An unexpected error occurred. Please try again." 
    };
  }
}

// Create new organization
export async function createOrganization(organizationData: OrganizationData): Promise<{
  success: boolean;
  message: string;
}> {
  try {
    const supabase = await createClient();
    
    // Get current user
    const { data: { user }, error: userError } = await supabase.auth.getUser();
    
    if (userError || !user) {
      return { success: false, message: "User not authenticated" };
    }

    // Check if user is already in an organization
    const { data: existingMember } = await supabase
      .from("organization_members")
      .select("id, organization:organizations(name)")
      .eq("user_id", user.id)
      .maybeSingle();

    if (existingMember) {
      const orgName = (existingMember.organization as unknown as { name: string })?.name || 'Unknown Organization';
      return { 
        success: false, 
        message: `You are already a member of "${orgName}". Please contact your admin if you need to create a new organization.` 
      };
    }

    // Check if organization name already exists
    const { data: existingOrg } = await supabase
      .from("organizations")
      .select("id, name")
      .eq("name", organizationData.name.trim())
      .maybeSingle();

    if (existingOrg) {
      return { 
        success: false, 
        message: `An organization with the name "${organizationData.name}" already exists. Please choose a different name.` 
      };
    }

    // Generate unique invitation code
    let invCode = generateInvitationCode();
    let isUnique = false;
    let attempts = 0;
    
    while (!isUnique && attempts < 5) {
      const { data: codeCheck } = await supabase
        .from("organizations")
        .select("id")
        .eq("inv_code", invCode)
        .maybeSingle();
        
      if (!codeCheck) {
        isUnique = true;
      } else {
        invCode = generateInvitationCode();
        attempts++;
      }
    }

    if (!isUnique) {
      return { success: false, message: "Failed to generate unique invitation code. Please try again." };
    }

    // Generate organization code based on name
    let orgCode = organizationData.name.trim()
      .toUpperCase()
      .replace(/[^A-Z0-9]/g, '')
      .substring(0, 8)
      .padEnd(3, '0');
    
    // Ensure code uniqueness
    let codeUnique = false;
    let codeAttempts = 0;
    
    while (!codeUnique && codeAttempts < 10) {
      const { data: codeCheck } = await supabase
        .from("organizations")
        .select("id")
        .eq("code", orgCode)
        .maybeSingle();
        
      if (!codeCheck) {
        codeUnique = true;
      } else {
        // Add numeric suffix to make it unique
        orgCode = orgCode.substring(0, 6) + String(codeAttempts + 1).padStart(2, '0');
        codeAttempts++;
      }
    }
    
    if (!codeUnique) {
      return { success: false, message: "Failed to generate unique organization code. Please try again." };
    }

    // Create organization with is_active = false (pending approval)
    const { data: newOrganization, error: orgError } = await supabase
      .from("organizations")
      .insert({
        code: orgCode,
        name: organizationData.name.trim(),
        description: organizationData.description.trim() || null,
        address: organizationData.address.trim() || null,
        phone: organizationData.phone.trim() || null,
        website: organizationData.website.trim() || null,
        industry: organizationData.industry.trim() || null,
        country_code: 'ID', // Default to Indonesia
        inv_code: invCode,
        is_active: false, // Pending approval
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
      })
      .select("id, name")
      .single();

    if (orgError) {
      logger.error("Organization creation error:", orgError);
      return { success: false, message: "Failed to create organization. Please try again." };
    }

    // Add user as organization member (without biodata, so they won't appear in export)
    // This is needed so creator can access the organization
    const { error: memberError } = await supabase
      .from("organization_members")
      .insert({
        organization_id: newOrganization.id,
        user_id: user.id,
        hire_date: new Date().toISOString().split('T')[0],
        employment_status: 'active',
        contract_type: 'permanent',
        is_active: false, // Will be activated when organization is approved
        // No biodata_nik - creator won't appear in export (filtered out)
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
      });

    if (memberError) {
      logger.error("Member creation error:", memberError);
      
      // Cleanup: delete the organization if member creation fails
      await supabase
        .from("organizations")
        .delete()
        .eq("id", newOrganization.id);
        
      return { success: false, message: "Failed to create organization member record. Please try again." };
    }

    return { 
      success: true, 
      message: `Organization "${newOrganization.name}" has been created successfully! Your request is pending admin approval. You'll be notified once it's approved.` 
    };

  } catch (error: unknown) {
    logger.error("Create organization error:", error);
    return { 
      success: false, 
      message: "An unexpected error occurred while creating the organization. Please try again." 
    };
  }
}

// Auto-activate member when organization is approved
// NOTE: This only activates if member was previously inactive DUE TO organization being inactive
// It will NOT activate members who were manually deactivated by admin
export async function autoActivateMemberIfOrgActive(): Promise<{
  success: boolean;
  message: string;
}> {
  try {
    const supabase = await createClient();
    
    // Get current user
    const { data: { user }, error: userError } = await supabase.auth.getUser();
    
    if (userError || !user) {
      return { success: false, message: "User not authenticated" };
    }

    // Check if user has organization membership with active org but inactive member
    const { data: member } = await supabase
      .from("organization_members")
      .select(`
        id,
        is_active,
        employment_status,
        created_at,
        updated_at,
        organization:organizations(
          id,
          name,
          is_active
        )
      `)
      .eq("user_id", user.id)
      .maybeSingle();

    if (!member || !member.organization) {
      return { success: false, message: "No organization membership found" };
    }

    const organization = member.organization as unknown as { id: string; name: string; is_active: boolean };
    
    // IMPORTANT: Only auto-activate if:
    // 1. Organization is active
    // 2. Member is inactive
    // 3. Member's created_at and updated_at are very close (meaning never manually updated)
    //    This prevents reactivating members who were intentionally deactivated by admin
    const createdAt = new Date(member.created_at).getTime();
    const updatedAt = new Date(member.updated_at).getTime();
    const timeDiff = Math.abs(updatedAt - createdAt);
    const wasNeverManuallyUpdated = timeDiff < 5000; // Less than 5 seconds difference
    
    if (organization.is_active && !member.is_active && wasNeverManuallyUpdated) {
      // Only activate if member was created inactive due to org being inactive (onboarding case)
      const { error: updateError } = await supabase
        .from("organization_members")
        .update({
          is_active: true,
          updated_at: new Date().toISOString()
        })
        .eq("id", member.id);

      if (updateError) {
        logger.error("Member activation error:", updateError);
        return { success: false, message: "Failed to activate member" };
      }

      return { success: true, message: "Member activated successfully" };
    }

    // If member was manually deactivated (updated_at differs from created_at significantly),
    // do NOT auto-activate
    return { success: true, message: "No activation needed" };

  } catch (error: unknown) {
    logger.error("Auto activate member error:", error);
    return { success: false, message: "An unexpected error occurred" };
  }
}

// Check user organization status
export async function checkUserOrganizationStatus(): Promise<{
  hasOrganization: boolean;
  organization?: {
    id: string;
    name: string;
    is_active: boolean;
  };
  memberStatus?: {
    is_active: boolean;
    employment_status: string;
  };
}> {
  try {
    const supabase = await createClient();
    
    // Get current user
    const { data: { user }, error: userError } = await supabase.auth.getUser();
    
    if (userError || !user) {
      return { hasOrganization: false };
    }

    // Check organization membership
    const { data: member } = await supabase
      .from("organization_members")
      .select(`
        is_active,
        employment_status,
        organization:organizations(
          id,
          name,
          is_active
        )
      `)
      .eq("user_id", user.id)
      .maybeSingle();

    if (!member || !member.organization) {
      return { hasOrganization: false };
    }

    const organization = member.organization as unknown as { id: string; name: string; is_active: boolean };
    return {
      hasOrganization: true,
      organization: organization,
      memberStatus: {
        is_active: member.is_active,
        employment_status: member.employment_status
      }
    };

  } catch (error: unknown) {
    logger.error("Check organization status error:", error);
    return { hasOrganization: false };
  }
}
