
import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import { PaymentEntry } from "@/lib/data/dummy-data";
import { format } from "date-fns";

export const generateReceipt = (payment: PaymentEntry) => {
    const doc = new jsPDF();

    // Defines
    const margin = 20;
    let yPos = 20;


    // --- Header ---
    doc.setFontSize(22);
    doc.setFont("helvetica", "bold");
    doc.text("Absensi Payment Receipt", margin, yPos);
    yPos += 15;

    // --- Organization ---
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text("Organization:", margin, yPos);
    yPos += 6;
    doc.setFont("helvetica", "normal");
    doc.text("Acme Solutions", margin, yPos);
    yPos += 12;

    // --- Employee ---
    doc.setFont("helvetica", "bold");
    doc.text("Employee:", margin, yPos);
    yPos += 6;
    doc.setFont("helvetica", "normal");
    doc.text(payment.member.name, margin, yPos);
    yPos += 6;
    doc.text(`${payment.member.name.toLowerCase().replace(' ', '.')}@email.com`, margin, yPos); // Mock email
    yPos += 12;

    // --- Pay Period ---
    doc.setFont("helvetica", "bold");
    doc.text("Pay Period:", margin, yPos);
    yPos += 6;
    doc.setFont("helvetica", "normal");
    const payDate = new Date(payment.date);
    const startDate = new Date(payDate);
    startDate.setDate(payDate.getDate() - 7);
    doc.text(`${format(startDate, 'MMMM d, yyyy')} – ${format(payDate, 'MMMM d, yyyy')}`, margin, yPos);
    yPos += 12;

    // --- Payment Date ---
    doc.setFont("helvetica", "bold");
    doc.text("Payment Date:", margin, yPos);
    yPos += 6;
    doc.setFont("helvetica", "normal");
    doc.text(format(payDate, 'MMMM d, yyyy'), margin, yPos);
    yPos += 12;

    // --- Payment Method ---
    doc.setFont("helvetica", "bold");
    doc.text("Payment Method:", margin, yPos);
    yPos += 6;
    doc.setFont("helvetica", "normal");
    doc.text(payment.method, margin, yPos);
    yPos += 12;

    // --- Payment Status ---
    doc.setFont("helvetica", "bold");
    doc.text("Payment Status:", margin, yPos);
    yPos += 6;
    doc.setFont("helvetica", "normal");
    doc.text(payment.status, margin, yPos);
    yPos += 15;

    // --- Breakdown Table ---
    doc.setFont("helvetica", "bold");
    doc.text("Payment Breakdown:", margin, yPos);
    yPos += 6;

    const tableBody = [
        ["Regular Hours", payment.hours.toString(), formatCurrency(payment.rate) + "/hr", formatCurrency(payment.amount - payment.ptoAmount - payment.bonus + payment.deductions)], // Approximate
        ["PTO", payment.ptoAmount > 0 ? (payment.ptoAmount / payment.rate).toString() : "-", payment.ptoAmount > 0 ? formatCurrency(payment.rate) + "/hr" : "-", formatCurrency(payment.ptoAmount)],
        ["Bonus", "-", "-", formatCurrency(payment.bonus)],
        ["Deductions", "-", "-", formatCurrency(payment.deductions)],
        ["Total Paid", "", "", formatCurrency(payment.amount)]
    ];

    autoTable(doc, {
        startY: yPos,
        head: [["Description", "Hours/Amount", "Rate", "Total"]],
        body: tableBody,
        theme: 'plain',
        headStyles: { fontStyle: 'bold', fillColor: [240, 240, 240], textColor: 0 },
        styles: { fontSize: 10, cellPadding: 3 },
        columnStyles: {
            0: { cellWidth: 80 }, // Description
            1: { cellWidth: 30, halign: 'right' },
            2: { cellWidth: 30, halign: 'right' },
            3: { cellWidth: 30, halign: 'right' }
        },
        foot: [["", "", "Total Paid", formatCurrency(payment.amount)]],
        footStyles: { fontStyle: 'bold' }
    });

    yPos = (doc as any).lastAutoTable.finalY + 15;

    // --- Notes ---
    if (payment.notes) {
        doc.setFont("helvetica", "bold");
        doc.text("Notes:", margin, yPos);
        yPos += 6;
        doc.setFont("helvetica", "normal");
        doc.text(payment.notes, margin, yPos);
        yPos += 20;
    } else {
        yPos += 10;
    }

    // --- Footer ---
    doc.setFontSize(10);
    doc.setTextColor(150);
    doc.text("Generated by Absensi", margin, 280);

    // Save
    doc.save(`receipt-${payment.id}.pdf`);
};

const formatCurrency = (amount: number) => {
    return new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(amount).replace('$', 'Rp'); // Using Rp as per context, but format requested was $ in sample? "Rp" used in app. 
    // Wait, sample said "$25.00/hr". I should probably stick to app's currency (IDR) but maybe just use format from dummy data context.
    // The dummy data uses IDR. I will use IDR.
};
